### ISSUE TITLE
score_phase2 --db crashes: ModelStrategy.decide passes 3 args to _build_feature_dict (needs 6)

### ISSUE THREAD

**Issue by edwinsteele** [edwinsteele/fuel-price-signal#174]
## What

Running `uv run python -m fuel_signal.score_phase2 --model-name phase4_5seed_lock_post_cc_removal_with_spend` (no extra flags, default DB) crashes during the realised-spend backtest added by #171:

\`\`\`
File ".../fuel_signal/backtest.py", line 169, in decide
    features = _build_feature_dict(state, station_price, avg_price)
TypeError: _build_feature_dict() missing 3 required positional arguments:
'lga_mean', 'brand_mean', and 'stickiness_score'
\`\`\`

`score_phase2` finishes the test-set scoring (logloss 0.2676, τ=0.60) and then dies inside `aggregate_backtest` → `run_backtest` → `ModelStrategy.decide` before `log_experiment` is reached, so nothing is written to results.csv.

## Why I noticed this

User asked me to run `score_phase2` to persist realised-spend cost metrics for the current Phase 4 lock (the acceptance criterion of #161, the issue #171 closed). The wiring in `score_phase2.run_realised_spend_backtest` works as intended, but the backtest's per-row `decide()` call is unrunnable for any model whose feature vector includes the Phase 4 additions (`lga_mean_cents`, `brand_mean_cents`, `stickiness_score`, and the derived `station_minus_*` columns).

This isn't a regression introduced by #171 — `ModelStrategy.decide` has been broken for the Phase 4 feature set since those features were added to `_build_feature_dict`. #171 just exposes the breakage by wiring the backtest into score_phase2's default path. Phase 2 logreg backtest (10 features) presumably also breaks the same way today.

## Files likely affected

- `fuel_signal/backtest.py` — `ModelStrategy.decide` (line 159–172) and `_build_feature_dict` call (line 169)
- `fuel_signal/backtest.py` — `PriceHistory` probably needs new lookups for LGA mean, brand mean, and per-station stickiness score on a given `as_of` date
- Possibly `fuel_signal/features.py` if we extract a shared "compute Phase 4 features at as_of" helper

## Design questions

1. Where do `lga_mean`, `brand_mean`, `stickiness_score` come from at backtest time? Options:
   - Look them up from the `daily_prices` + `station_class` + `lga_leadership` tables on demand (slow per-row but exact, matches training-time semantics)
   - Pre-compute a (date × station) feature table once at the start of the backtest (much faster; effectively reuses `data/features.csv`)
   - Pass the precomputed `features.csv` into the backtest engine so it can index directly
2. How are NaNs handled? The training-time pipeline tolerates None for the LGA/brand/stickiness columns; the backtest currently has no equivalent guard.
3. Should we add a regression test that runs `aggregate_backtest` with a Phase 4 calibrated artifact on a tiny synthetic DB so this can never crash silently again?

## Acceptance criteria

- [ ] `uv run python -m fuel_signal.score_phase2` against the current `data/models/lgbm_calibrated.joblib` (Phase 4, 15 features) runs to completion and appends a results.csv row with non-empty `realised_spend_cpl` and `realised_savings_vs_always_buy_pct`
- [ ] `uv run python -m fuel_signal.backtest_phase2 --model-path data/models/logreg_calibrated.joblib --no-patch` (Phase 2 path) still works, or is explicitly documented as no-longer-supported
- [ ] Test added that exercises `ModelStrategy.decide` against a Phase 4 calibrated artifact
